version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "8080:8080"
  nginx:
    image: nginx
    ports:
      - "80:80"
  pgAdmin:
    image: elestio/pgadmin
    ports:
      - "8081:8081"